package uk.ac.nottingham.cryptography.modes;

import uk.ac.nottingham.cryptography.ciphers.BlockCipher;

import java.util.function.Supplier;

/**
 * Interface representing a tweakable cipher mode. Provides
 * simple functions for initialisation, encryption and
 * decryption.
 * <br/>
 * Do not edit this file.
 */
public interface TweakableCipherMode {
    void initialise(Supplier<BlockCipher> cipherSupplier, byte[] key);
    void encrypt(byte[] sector, byte[] data);
    void decrypt(byte[] sector, byte[] data);
}
