package uk.ac.nottingham.cryptography.tests.modes;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
  Parses NIST and other test vectors for use in the XTS tests.

  Do not edit this file.
 */
public final class XTSTestVectorParser {

    private XTSTestVectorParser() {}

    public static List<XTSTestVector> load(String resourcePath) throws IOException {
        try (InputStream is = XTSTestVectorParser.class
                .getClassLoader()
                .getResourceAsStream(resourcePath)) {
            if (is == null) {
                throw new IOException("Resource not found on classpath: " + resourcePath);
            }
            return parse(new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8)));
        }
    }

    private static List<XTSTestVector> parse(BufferedReader reader) throws IOException {
        List<XTSTestVector> vectors = new ArrayList<>();

        String  line;

        while ((line = reader.readLine()) != null) {
            line = line.strip();

            String[] e = line.split(",");

            XTSTestVector vec = new XTSTestVector(
                    e[0].equals("ENCRYPT"),
                    Integer.parseInt(e[1]),
                    e[2],
                    e[3],
                    e[4],
                    e[5]
            );
            vectors.add(vec);
        }
        return vectors;
    }
}
