package uk.ac.nottingham.cryptography.ciphers;

/**
 * Interface representing an implementation of a BlockCipher
 * encryption.
 * <p>
 * Provides a function to initialise a cipher using a secret
 * key, and separate encrypt and decrypt functions that will
 * encrypt or decrypt a single block of data, writing the
 * result into the supplied output array.
 * <p>
 * Do not edit this file.
 */
public interface BlockCipher {
    /**
     * Initialise the block cipher with the provided key.
     * @param key Byte array representing the secret key in big-
     *            endian order. All implementing functions in
     *            this project assume keys will be 128-bits.
     */
    void initialise(byte[] key);

    /**
     * Encrypt a single block of data under the key provided during
     * initialisation. The input should not be altered, and the result
     * should be returned in the provided output array.
     * @param input 128-bit byte array of plaintext
     * @param output 128-bit byte array that will be populated by the
     *               computed ciphertext.
     */
    void encrypt(byte[] input, byte[] output);

    /**
     * Decrypt a single block of data under the key provided during
     * initialisation. The input should not be altered, and the result
     * should be returned in the provided output array.
     * @param input 128-bit byte array of ciphertext
     * @param output 128-bit byte array that will be populated by the
     *               computed plaintext.
     */
    void decrypt(byte[] input, byte[] output);
}
