package uk.ac.nottingham.cryptography.ciphers;

/**
 * Interface representing the internal function logic of
 * the Zodiac block cipher.
 * <p>
 * This class is used by the test suite to expose various
 * internal functions for testing, that might otherwise be
 * left private in a typical implementation. Details on these
 * functions can be found in the coursework specification.
 * <p>
 * Do not edit this file.
 */
public interface ZodiacCipher {
    void F(byte[] b);
    void initPads(byte[] dpad, byte[] kpad, byte[] key);
    void PI(byte[] block);
    void PSI(byte[] block);
    byte[][] generateSchedule(byte[] dpad, byte[] kpad);
    void initialise(byte[] key);
    void encrypt(byte[] input, byte[] output);
    void decrypt(byte[] input, byte[] output);
}
